{{- if eq .Values.global.env "Testing" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.service.testing.name }}
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: {{ .Values.flask.service.testing.port }}
      targetPort: {{ .Values.flask.service.testing.targetPort }}
  type: {{ .Values.flask.service.testing.type }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
spec:
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}
  type: {{ .Values.mysql.service.type }}
---
{{- if eq .Values.global.env "Production" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.service.production.name }}
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: {{ .Values.flask.service.production.port }}
      targetPort: {{ .Values.flask.service.production.targetPort }}
  type: {{ .Values.flask.service.production.type }}
{{- end }}